<?php
$this->headLink()->appendStylesheet($this->basePath('css/grid.css'))
?>
<div class="row-fluid">
    <div class="col-md-10 col-md-offset-1">
        <div class="container  panel panel-default">
            <div class="containerFormGrid">
                <div class="shadow-none p-1 mb-5 bg-light containerFormGrid">
                    <svg class="bg-light icon align-top"><use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-pencil"></use></svg><?php echo $this->translate('Edit/Insert'); ?>
                    &nbsp;<strong>[<?php echo $this->translate($this->title); ?>]</strong>
                </div>
                <?php
                $row = 0;
                $form = $this->crudform;
                $form->prepare();
                $formAttributes = $form->getAttributes();
                if (!array_key_exists('action', $formAttributes)) {
                    $form->setAttribute('action', $_SERVER['REQUEST_URI']);
                }
                echo $this->form()->openTag($form);
                echo '<div class="control-group">';
                foreach ($form as $elm) {
                    if ($elm->getName() == 'submit' || $elm->getName() == 'cancel') continue;
                    if ($elm->getAttribute('type') == 'hidden') {
                        $hiddenElemet[] = $elm;
                        continue;
                    }
                    if ($row % 2 == 0) {
                        echo '<div class="row">';
                    }
                    echo '<div class="col-md-6">';
                    echo '<label class="control-label"  for="' . $elm->getName() . '">' . $elm->getLabel() . '</label>';
                    echo '<div class="form-group">';
                    if ($elm instanceof \Zf2datatable\Form\Element\DateCalendar) {
                        echo '<div class="it-datepicker-wrapper">';
                        echo $this->zf2formdatecalendar($elm);
                        echo '</div>';
                    } elseif ($elm instanceof \Zf2datatable\Form\Element\DateTimeCalendar) {
                        echo $this->zf2formdatetimecalendar($elm);
                    } elseif ($elm instanceof \Zf2datatable\Form\Element\CKEditor) {
                        echo $this->formckeditor($elm);
                    }
                    elseif ($elm instanceof \Laminas\Form\Element\Radio) {
                        $label          = $elm->getLabel();
                        $id             = $elm->getAttribute("id");
                        $name           = $elm->getAttribute("name");
                        $cheked         =  $elm->getAttribute("checked");
                        echo "
                            <div class=\"form-check form-check-group\">
                            <input id=\"$id\" type=\"checkbox\" checked=\"$cheked\" name=\"$name\">
                            <label for=\"$id\">$label</label>
                          </div>
                        ";
                    }
                    else {
                        $elm->setAttribute("class", "form-control");
                        echo $this->formElement($elm);
                    }

                    echo $this->formelementerrors($elm, array('class' => "error"));
                    echo '</div>';
                    echo '</div>';
                    if ($row % 2 != 0) {
                        echo '</div>';
                        $row = 0;
                    } else
                        $row++;
                }
                echo '</div>';
                $row++;
                echo '<br />';
                if (is_array($hiddenElemet)) {
                    foreach ($hiddenElemet as $elm) {
                        echo $this->formElement($elm);
                    }
                }
                echo '<div class="row"><div class="col-md-4">';
                $form->get('submit')->setAttribute("class","btn btn-success");
                $form->get('cancel')->setAttribute("class","btn btn-info");


                echo $this->formButton($form->get('submit'), $this->translate('Salva'));
                echo '&nbsp;&nbsp;';
                echo $this->formButton($form->get('cancel'), $this->translate('Anulla Operazione'));
                echo '</div></div>';

                //echo $this->formCollection($this->crudform);
                echo $this->form()->closeTag();

                $controller = substr($this->main_ruote["controller"], strrpos($this->main_ruote["controller"], '\\') + 1);
                $action = $this->main_ruote["action"];
                ?>
            </div>
        </div>
    </div>
</div>
<?php $this->placeholder('bottomScripts')->captureStart(); ?>
<script language="JavaScript">
    jQuery(document).ready(function () {
        <?php echo $jsCodeElement;?>
        <?php echo $injectedJsFormCode;?>
        $('#cancelbutton').click(function () {
            <?php $redirect = ($this->redirect_url !== '') ? $this->serverUrl() . $this->redirect_url : $this->serverUrl() . $this->url($this->main_ruote["routeName"],
                array('controller' => $controller,
                    'action' => $action));?>
            window.location.href = "<?php  echo $redirect;?>";
        });
        $(document).on('click','#submitbutton',function () {
            $.LoadingOverlay("show");
        })
    });
</script>
<?php $this->placeholder('bottomScripts')->captureEnd() ?>
