    <?php
    use Zf2datatable\Column\Type;

    $hasMassActions = false;
    if(count($this->massActions) > 0){
        $hasMassActions = true;
    }

    //hasMassActions = true;

    ?>

    <style>
    <!--
    .loader
        {
            background: url(<?php echo $this->basePath(); ?>/img/ajax-loader.gif);
            background-repeat: no-repeat;
            background-position: right;
        }
    -->
    </style>
    <div class="row-fluid">
        <div class="col-md-12">
                 <div class="control-group">
                           <div class="controls">
                                <?php
                                if (!empty($this->successMessages)) {
                                    $messages = array_unique($this->successMessages);
                                    foreach ($messages as $msg) {
                                        ?>
                                        <div class="alert alert-success alert-dismissable">
                                            <button type="button" class="close" data-dismiss="alert"  aria-hidden="true">&times;</button>
                                            <?= $msg; ?>
                                        </div>
                                    <?php
                                    }
                                }
                                ?>
                           </div>
                 </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="col-md-12">
        <?php if ($this->daterangeEnabled): ?>
            <?php  $this->inlineScript()->captureStart();?>



            function submitForm(){
                        beforeSubmitGrid();
                        $('#form_<?php echo $this->gridId; ?>').submit();
            }

            function beforeSubmitGrid(){
                        $('.daterange').each(function(key,value){
                        var filtro = $(this).val();
                        if(filtro !=''){
                                var regex = /^>/gi;
                                match = regex.exec(filtro);
                                if(match){
                                filtro = filtro.replace('>= ','');
                                filtro = filtro.replace(',',' - ');
                                $(this).val(filtro);
                                }
                            }

                        });
             }

            $( "input[name^='toolbarFilters']" ).focus(function(){
                                    $(this).val('');
            });


            $(document).ready(function(){

                jQuery('a > span').on('click',function(event) {
                    if($(this).hasClass( 'glyphicon glyphicon-trash' )){
                        event.preventDefault();
                        var r=confirm("<?php echo $this->translate("Are you sure you want to delete?");?>");
                        if (r==true)   {
                           window.location = $(this).parent().attr('href');
                        }
                    }
                });
                <?php //If daterange bootstrapTable filter is enable show it ?>
                    $('a').click(function(){
                        beforeSubmitGrid();
                    });

                    $('#clearfilter').click(function(){
                        $("input[name^='toolbarFilters']").val("");
                        $("select[name^='toolbarFilters']").val("");
                        $("#form_<?php echo $this->gridId; ?>").submit();
                    });



                    $('input.daterange').daterangepicker(
                    <?= Laminas\Json\Json::encode($this->daterangeParameters, false, array('enableJsonExprFinder' => true)); ?>
                    ).on('apply.daterangepicker', function(ev,picker){
                        beforeSubmitGrid();
                        this.form.submit();
                    });

                    $('[data-toggle="popover"]').popover();

               });
            <?php $this->inlineScript()->captureEnd(); ?>
        <?php endif; ?>

   <?php echo $this->toolbar; ?>
   <?php echo $this->partial($this->templateToolbar);?>
    <form name="form_<?php echo $this->gridId; ?>" id="form_<?php echo $this->gridId; ?>" method="<?php echo $this->filterMethod;?>" action="<?php echo $this->url(null, array(), array(), true); ?>">
        <input type="submit" style="width: 0px; height:0px; margin: 0; padding: 0; border: 0;" name="hiddenSubmit" />
        <input type="hidden" name="gridID" value="<?php echo $this->gridId;?>" />
        <input type="hidden" name="<?php echo $this->parameterNames['sortColumns']; ?>" value="<?php echo $this->activeParameters[$this->parameterNames['sortColumns']]; ?>" />
        <input type="hidden" name="<?php echo $this->parameterNames['sortDirections']; ?>" value="<?php echo $this->activeParameters[$this->parameterNames['sortDirections']]; ?>" />
    <?php
    $orderOnclick = 'document.forms[\'form_'.$this->gridId.'\'].elements[\'' . $this->parameterNames['sortColumns'] . '\'].value = \'%s\';';
    $orderOnclick.= 'document.forms[\'form_'.$this->gridId.'\'].elements[\'' . $this->parameterNames['sortDirections'] . '\'].value = \'%s\';';
    $orderOnclick.= 'document.forms[\'form_'.$this->gridId.'\'].submit(); return false;';

    $classes = array('table', 'table-striped', 'table-bordered','table-hover');
    if($this->rowClickAction !== null){
        $classes[] = 'table-hover';
    }
    ?>

	<?php if(isset($this->childModelMiddle)):?>
        <div class="row">
        	<div class="col-md-12 text-center">
            <?php echo $this->childModelMiddle;?>
            </div>
        </div>
	<?php endif;?>
    <?php echo $this->childModelFilter;?><!-- todo -->
    <?php if ($this->additionalFilters):?>
    <table class="<?php echo implode(' ', $classes); ?>"  style="background-color:#DEE1EA;width:100%;font-size:0.8em">
        <thead>
            <tr style="background-color: #EEE">
                <td>
                    <table>
                        <thead>
                            <tr>
                                <?php foreach($this->columns as $col):?>
                                    <?php if($col->getIsHiddenButShowFilter() === true):?>
                                        <th><label for="<?php echo $col->getUniqueId();?>" ><?php echo $col->getLabel();?></label></th>
                                    <?php endif;?>
                              <?php endforeach;?>
                            </tr>
                        </thead>
                        <tbody>
                           <tr>
                                <?php foreach($this->columns as $col):?>
                                    <?php if($col->getIsHiddenButShowFilter() === true):?>
                                        <?php $htmlFilter = '';
                                        if ($col->isUserFilterEnabled() === true) {
                                            if ($col->hasFilterSelectOptions() === true) {
                                                $htmlFilter = '<select name="toolbarFilters[' . $col->getUniqueId() . ']" style="width:80%" onchange="javascript:submitForm();" class="form-control" >';
                                                foreach ($col->getFilterSelectOptions() as $value => $option) {
                                                    if ($col->getFilterActiveValue() == sprintf($col->getFilterDefaultOperation(), $value)) {
                                                        $htmlFilter .= '<option value="' . $value . '" selected="selected">' . $option . '</option>';
                                                    } else if (($col->getFilterActiveValue() == '') && ($value === '')){
                                                        $htmlFilter .= '<option value="' . $value . '" selected="selected">' . $option . '</option>';
                                                    } else {
                                                        $htmlFilter .= '<option value="' . $value . '">' . $option . '</option>';
                                                    }
                                                }
                                                $htmlFilter .= '</select>';

                                            } else if ($col->getType() instanceof \Zf2datatable\Column\Type\DateTime){
                                                $htmlFilter = '<input type="text" id="' . $col->getUniqueId() . '_ID" name="toolbarFilters[' . $col->getUniqueId() . ']" style="width:150px" value="' . $col->getFilterActiveValue() . '" class="daterange class="form-control"" />';
                                            } else {
                                                $htmlFilter = '<input type="text" id="' . $col->getUniqueId() . '_ID" name="toolbarFilters[' . $col->getUniqueId() . ']" style="width:150px" value="' . $col->getFilterActiveValue() . '" class="form-control" />';
                                            }
                                        }
                                        ?>
                                    <td class="<?php echo implode(',', $classes); ?>">
                                        <?php echo $htmlFilter; ?>
                                    </td>
                                  <?php endif;?>
                              <?php endforeach;?>
                            </tr>
                       </tbody>
                   </table>
                 </td>
            </tr>
        </thead>
     </table>
     <?php endif?>
        <table class="<?php echo implode(' ', $classes); ?>"  style="background-color:#FFFFFF;width:100%">
          <thead>
            <tr style="background-color: #EEE">
                <?php
                if($hasMassActions === true){
                    echo '<th width="1%">
                        <input type="checkbox" onclick="' . $this->gridId . '_toggleCheckboxes(this);" /></th>
                    ';

                }

                foreach($this->columns as $col){
                    /* @var $col \Zf2datatable\Column\AbstractColumn */
                    $classes = array();
                    $styles = array();


                   $type =$col->getType();
                   if($type instanceof \Zf2datatable\Column\Type\AutoComplete){
                      $js=<<<JS
                $("#{$col->getUniqueId()}_ID").autocomplete({
                        source:'{$this->uriRedirectJson}?op=j&column={$col->getUniqueId()}',
                        minLength: 3,
                        autoFill: true,
                        mustMatch:true,dev-master
                        delay: 0,//0
                        cacheLength: 1,
                        max:30,
                         select: function( event, ui ) {
                         //add(event, ui);
                         //utilizzare questo spazio per valorizzare ad esempio dei campi input con altri dati prelevati da db
                         //$("#campo_nascosto").val(ui.item.nome_campo_array_settato_in_lista-utenti);
                         },
                        search: function (e, u) {
                            $(this).addClass('loader');
                        },
                        response: function (e, u) {
                            $(this).removeClass('loader');
                        }
                 });
JS;
                   $jsOutPut.= $js;
                      //$this->placeholder('bottomScripts')->append($js);
                   }

                    $id = $col->getUniqueId();

                    $label = '';
                    if($col->getLabel() != ''){
                        $label = $this->translate($col->getLabel());
                    }

                    $width = $col->getWidth();
                    if($width != ''){
                        $styles[] = 'width:'.$this->escapehtmlattr($width).'px';
                    }


                    if($col->isHidden() === true){
                        $classes[] = 'hidden';
                    }
                    if($col->getType() instanceof Type\Number){
                        $styles[] = 'text-align: right';
                    }
                    else{
                        $styles[] = 'text-align: center';
                    }
                    ?>
                    <th id="<?php echo $this->escapehtmlattr($id); ?>" class="<?php echo implode(',', $classes); ?>" style="<?php echo implode(';', $styles); ?>">

                        <?php if($col->isUserSortEnabled() === true):
                            if($col->isSortActive() === true && $col->getSortActiveDirection() === 'ASC'){
                                $direction = 'DESC';
                            } else{
                                $direction = 'ASC';
                            }
                            ?>
                            <a href="<?php echo
                                $this->url(null,
                                    array(),
                                    array(
                                        'query' => array_merge($this->activeParameters, array(
                                                $this->parameterNames['sortColumns'] => $col->getUniqueId(),
                                                $this->parameterNames['sortDirections'] => $direction,
                                                "gridID"=>$this->gridId
                                            )
                                        )
                                    ),
                                    true
                                );?>
                            " onclick="<?php echo sprintf($orderOnclick, $col->getUniqueId(), $direction); ?>">
                                <?php echo $this->escapeHtml($label); ?>
                            </a>
                        <?php else: ?>
                            <?php echo $this->escapeHtml($label); ?>
                        <?php endif; ?>

                        <?php
                        if($col->isSortActive() === true){
                            if($col->getSortActiveDirection() === 'ASC'):?>
                                <i class="icon-chevron-down glyphicon glyphicon-chevron-down"></i>
                            <?php else: ?>
                                <i class="icon-chevron-up glyphicon glyphicon-chevron-up"></i>
                            <?php endif;
                        }
                        ?>
                    </th>
                    <?php
                    }
                    ?>
            </tr>

            <!-- User filters -->
            <?php if($this->isUserFilterEnabled === true):?>
                <tr style="background-color:#EEE; text-align:right">
                    <?php
                    if($hasMassActions === true){
                        echo '<td></td>';
                    }
                    foreach($this->columns as $col){
                        /* @var $col \Zf2datatable\Column\AbstractColumn */
                        $classes = array();
                        if($col->isHidden() === true){
                            $classes[] = 'hidden';
                        }

                        $htmlFilter = '';
                        if ($col->isUserFilterEnabled() === true) {

                            $width = $col->getWidth();
                            if ($col->hasFilterSelectOptions() === true) {
                                $htmlFilter = '<select name="toolbarFilters[' . $col->getUniqueId() . ']"  onchange="javascript:submitForm();"  style="width:90%" class="form-control">';
                                foreach ($col->getFilterSelectOptions() as $value => $option) {
                                    if ($col->getFilterActiveValue() == sprintf($col->getFilterDefaultOperation(), $value)) {
                                        $htmlFilter .= '<option value="' . $value . '" selected="selected">' . $option . '</option>';
                                    } else if (($col->getFilterActiveValue() == '') && ($value === '')){
                                        $htmlFilter .= '<option value="' . $value . '" selected="selected">' . $option . '</option>';
                                    } else {
                                        $htmlFilter .= '<option value="' . $value . '">' . $option . '</option>';
                                    }
                                }
                                $htmlFilter .= '</select>';

                            } else if ($col->getType() instanceof \Zf2datatable\Column\Type\DateTime){
                                $htmlFilter = '<input type="text" id="' . $col->getUniqueId() . '_ID" name="toolbarFilters[' . $col->getUniqueId() . ']" style="width:90%" value="' . $col->getFilterActiveValue() . '" class="daterange" />';
                            } else {
                                $htmlFilter = '<input type="text" id="' . $col->getUniqueId() . '_ID" name="toolbarFilters[' . $col->getUniqueId() . ']" style="width:90%"  value="' . $col->getFilterActiveValue() . '" class="form-control" />';
                            }
                        }
                        ?>
                        <td class="<?php echo implode(',', $classes); ?>" style="width:<?php echo $width?>px">
                            <?php if($col->getIsHiddenButShowFilter() === false): ?>
                                <?php echo $htmlFilter; ?>
                            <?php endif;?>
                        </td>
                        <?php
                    }
                ?>
                </tr>
            <?php endif; ?>
        </thead><!-- END table header -->

        <!-- Start table BODY -->
        <tbody>
        <?php $prevRow = null;?>
        <?php foreach($this->data as $row): ?>
            <?php
            if($this->showAggregate)  $this->bootstrapTableAggregate()->aggregateData($row, $this->columns);

            if($this->hideDuplicate){
                if( $row != $prevRow){
                    echo $this->bootstrapTableRow($row, $this->columns, $this->rowClickAction, $this->rowStyles, $hasMassActions);
                }
            }
            else
                echo $this->bootstrapTableRow($row, $this->columns, $this->rowClickAction, $this->rowStyles, $hasMassActions);


            ?>
            <?php $prevRow = $row;?>
        <?php endforeach; ?>
        <?php  $this->bootstrapTableAggregate()->drawRow();?>
        </tbody>
    </table>
    <?php echo $this->partial('zf2datatable/renderer/bootstrapTable/footer'); ?>
    </form>
        <?php echo $this->childModelBottom;?>
        </div>
    </div>
</div>
    <?php //$this->placeholder('bottomScripts')->append('});')?>
    <?php //$this->placeholder('bottomScripts')->append('</script>')?>

    <?php  $this->inlineScript()->captureStart();?>
     $(document).ready(function(){
     	<?php echo isset($jsOutPut) ?? '';?>
     });
    <?php $this->inlineScript()->captureEnd(); ?>

    <script type="text/javascript">
        <?php $this->placeholder('bottomScripts')->captureStart(); ?>
        <?php echo $this->injectedJsCode;?>
        <?php echo $this->injectedJsFormCode;?>
        <?php $this->placeholder('bottomScripts')->captureEnd() ?>
    </script>

